name: CI
on:
  - pull_request
  - push

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: [1.26.x]
        nodeVer: [25]

    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Set up Go ${{ matrix.goVer }}
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.goVer }}
        cache-dependency-path: go.sum

    - name: Set up Node.js ${{ matrix.nodeVer }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.nodeVer }}
        cache: npm

    - name: Get dependencies
      run: go mod download

    - name: Install frontend dependencies
      run: npm ci

    - name: Check frontend assets
      run: npm run check

    - name: Build
      run: go build -v .
    
    - name: Format
      run: diff -u <(echo -n) <(gofmt -d $(git ls-files '*.go'))
    
    - name: Test
      run: go test ./...
